import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { OwnerService, OwnerDashboard, AvailabilityBlock } from '../../services/owner.service';
import { Property } from '../../services/property.service';
import { Booking } from '../../services/booking.service';

@Component({
  selector: 'app-owner-workspace', standalone: true, imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <section class="page"><header><div><span class="eyebrow">OWNER WORKSPACE</span><h1>Manage your rentals</h1><p>Keep listings, booking requests, and unavailable dates in one place.</p></div><a routerLink="/owner/add-property" class="button">Add property</a></header>
    <p class="error" *ngIf="error">{{ error }}</p><div class="loading" *ngIf="loading">Loading your workspace…</div>
    <ng-container *ngIf="!loading"><div class="metrics"><article><small>Properties</small><b>{{ dashboard.totalProperties }}</b></article><article><small>Approved</small><b>{{ dashboard.activeProperties }}</b></article><article><small>Pending requests</small><b>{{ dashboard.pendingBookingRequests }}</b></article><article><small>Estimated earnings</small><b>₹{{ dashboard.estimatedEarnings }}</b></article></div>
    <nav><button [class.selected]="tab === 'properties'" (click)="tab='properties'">Listings</button><button [class.selected]="tab === 'bookings'" (click)="tab='bookings'">Booking requests</button><button [class.selected]="tab === 'availability'" (click)="tab='availability'">Availability</button></nav>
    <section *ngIf="tab === 'properties'" class="panel"><h2>Your listings</h2><div class="empty" *ngIf="!properties.length">You have not created a listing yet.</div><article class="row" *ngFor="let property of properties"><div><strong>{{ property.title }}</strong><small>{{ property.location }} · ₹{{ property.pricePerNight }}/night</small></div><span class="status">{{ property.approvalStatus }}</span><button (click)="editing=property">Edit</button><button class="danger" (click)="deactivate(property)">Deactivate</button></article><form *ngIf="editing" class="edit-form" (ngSubmit)="updateProperty()"><h3>Edit {{editing.title}}</h3><input name="editTitle" [(ngModel)]="editing.title" required><textarea name="editDescription" [(ngModel)]="editing.description" required></textarea><input name="editLocation" [(ngModel)]="editing.location" required><input name="editPrice" type="number" [(ngModel)]="editing.pricePerNight" required><button>Save listing</button><button type="button" class="danger" (click)="editing=null">Cancel</button></form></section>
    <section *ngIf="tab === 'bookings'" class="panel"><h2>Booking requests and history</h2><div class="empty" *ngIf="!bookings.length">No bookings for your properties yet.</div><article class="row" *ngFor="let booking of bookings"><div><strong>{{ booking.propertyTitle }}</strong><small>{{ booking.checkIn }} to {{ booking.checkOut }} · {{ booking.location }}</small></div><span class="status">{{ booking.status }}</span><ng-container *ngIf="booking.status === 'PENDING'"><button (click)="decide(booking, 'ACCEPTED')">Accept</button><button class="danger" (click)="decide(booking, 'REJECTED')">Reject</button></ng-container></article></section>
    <section *ngIf="tab === 'availability'" class="panel"><h2>Block unavailable dates</h2><form class="block-form" (ngSubmit)="addBlock()"><select name="propertyId" [(ngModel)]="block.propertyId" required><option [ngValue]="null">Choose a property</option><option *ngFor="let property of properties" [ngValue]="property.id">{{ property.title }}</option></select><input name="start" type="date" [(ngModel)]="block.startDate" required><input name="end" type="date" [(ngModel)]="block.endDate" required><input name="reason" placeholder="Reason (optional)" [(ngModel)]="block.reason"><button [disabled]="!block.propertyId">Block dates</button></form><div class="empty" *ngIf="!availability.length">No unavailable periods saved.</div><article class="row" *ngFor="let item of availability"><div><strong>{{ propertyName(item.propertyId) }}</strong><small>{{ item.startDate }} to {{ item.endDate }}{{ item.reason ? ' · ' + item.reason : '' }}</small></div><button class="danger" (click)="removeBlock(item.id)">Remove</button></article></section></ng-container></section>`,
  styles: [`
    .page{max-width:1120px;margin:auto;padding:32px 20px;color:#172033}header{display:flex;justify-content:space-between;gap:16px;align-items:center;background:#153b4b;color:white;padding:28px;border-radius:22px}h1{margin:5px 0;font-size:32px}header p{margin:0;opacity:.85}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.12em}.button,button{border:0;border-radius:9px;padding:9px 12px;background:#146b75;color:white;font-weight:750;cursor:pointer;text-decoration:none}.button{background:white;color:#153b4b}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:20px 0}.metrics article,.panel{border:1px solid #e2e8f0;background:white;border-radius:14px;padding:16px}.metrics small,.row small{display:block;color:#64748b}.metrics b{font-size:25px}nav{display:flex;gap:8px;margin:18px 0}nav button{background:#e8eef2;color:#334155}nav .selected{background:#153b4b;color:white}.panel h2{margin-top:0}.row{display:flex;align-items:center;gap:10px;border-top:1px solid #edf2f7;padding:13px 0}.row>div{flex:1}.status{font-size:12px;font-weight:800;background:#eef6ff;padding:5px 8px;border-radius:999px}.danger{background:#b42318}.empty{padding:18px;color:#64748b;text-align:center}.block-form,.edit-form{display:grid;grid-template-columns:1.5fr 1fr 1fr 1.5fr auto;gap:8px;margin-bottom:14px}.edit-form{grid-template-columns:1fr 1fr}.edit-form h3{grid-column:1/-1;margin:8px 0}.block-form input,.block-form select,.edit-form input,.edit-form textarea{padding:9px;border:1px solid #cbd5e1;border-radius:9px}.loading,.error{margin:18px 0;padding:12px}.error{color:#b42318;background:#fef2f2}@media(max-width:720px){.metrics{grid-template-columns:repeat(2,1fr)}.block-form,.edit-form{grid-template-columns:1fr}.row{align-items:flex-start;flex-wrap:wrap}header{align-items:flex-start;flex-direction:column}}
  `]
})
export class OwnerWorkspaceComponent implements OnInit {
  dashboard: OwnerDashboard = { totalProperties: 0, activeProperties: 0, pendingProperties: 0, pendingBookingRequests: 0, acceptedBookings: 0, completedStays: 0, estimatedEarnings: 0 };
  properties: Property[] = []; bookings: Booking[] = []; availability: AvailabilityBlock[] = []; tab = 'properties'; loading = true; error = ''; editing: Property | null = null;
  block: { propertyId: number | null; startDate: string; endDate: string; reason: string } = { propertyId: null, startDate: '', endDate: '', reason: '' };
  constructor(private owner: OwnerService) {}
  ngOnInit() { this.reload(); }
  reload() { this.loading = true; this.error = ''; this.owner.dashboard().subscribe({ next: x => { this.dashboard=x; this.owner.properties().subscribe({next:p=>{this.properties=p; this.owner.bookings().subscribe({next:b=>{this.bookings=b; this.owner.availability().subscribe({next:a=>{this.availability=a;this.loading=false},error:e=>this.fail(e)})},error:e=>this.fail(e)})},error:e=>this.fail(e)}) }, error: e => this.fail(e) }); }
  fail(e: any) { this.error=e?.error?.message ?? 'Unable to load owner data.'; this.loading=false; }
  decide(booking: Booking, status: 'ACCEPTED'|'REJECTED') { this.owner.decideBooking(booking.id,status).subscribe({next:()=>this.reload(),error:e=>this.fail(e)}); }
  deactivate(property: Property) { this.owner.deactivateProperty(property.id).subscribe({next:()=>this.reload(),error:e=>this.fail(e)}); }
  updateProperty() { if (!this.editing) return; const { id, title, description, location, pricePerNight } = this.editing; this.owner.updateProperty(id, { title, description, location, pricePerNight }).subscribe({ next: () => { this.editing = null; this.reload(); }, error: e => this.fail(e) }); }
  addBlock() { if (!this.block.propertyId) return; this.owner.blockAvailability({ propertyId:this.block.propertyId,startDate:this.block.startDate,endDate:this.block.endDate,reason:this.block.reason }).subscribe({next:()=>{this.block={propertyId:null,startDate:'',endDate:'',reason:''};this.reload()},error:e=>this.fail(e)}); }
  removeBlock(id:number) { this.owner.removeAvailability(id).subscribe({next:()=>this.reload(),error:e=>this.fail(e)}); }
  propertyName(id:number) { return this.properties.find(p=>p.id===id)?.title ?? `Property #${id}`; }
}
