spring.application.name=property-rental

# MySQL Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/property_db
spring.datasource.username=root
spring.datasource.password=Mali@123

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Configuration
server.port=8080

# File Upload Configuration
app.upload.dir=uploads

