import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AdminService, AdminDashboard, AdminUser, Category, Complaint, Setting } from '../../services/admin.service';
import { Property } from '../../services/property.service';
import { Booking } from '../../services/booking.service';

@Component({
  selector: 'app-admin-workspace', standalone: true, imports: [CommonModule, FormsModule],
  template: `
  <section class="page"><header><span class="eyebrow">ADMINISTRATION</span><h1>Marketplace control centre</h1><p>Review listings, accounts, and operational records.</p></header><p class="error" *ngIf="error">{{error}}</p><div *ngIf="loading" class="loading">Loading administration data…</div>
  <ng-container *ngIf="!loading"><div class="metrics"><article><small>Users</small><b>{{ dashboard.totalUsers }}</b></article><article><small>Owners</small><b>{{ dashboard.totalOwners }}</b></article><article><small>Pending listings</small><b>{{ dashboard.pendingProperties }}</b></article><article><small>Open complaints</small><b>{{ dashboard.openComplaints }}</b></article></div>
  <nav><button *ngFor="let item of tabs" [class.selected]="tab===item.key" (click)="tab=item.key">{{item.label}}</button></nav>
  <section class="panel" *ngIf="tab==='properties'"><h2>Property approvals</h2><div class="empty" *ngIf="!properties.length">No properties found.</div><article class="row" *ngFor="let p of properties"><div><strong>{{p.title}}</strong><small>{{p.location}} · {{p.ownerEmail}} · ₹{{p.pricePerNight}}</small></div><span class="status">{{p.approvalStatus}}</span><ng-container *ngIf="p.approvalStatus==='PENDING'"><button (click)="moderate(p,'APPROVED')">Approve</button><button class="danger" (click)="moderate(p,'REJECTED')">Reject</button></ng-container><button class="danger" (click)="deleteProperty(p.id)">Delete</button></article></section>
  <section class="panel" *ngIf="tab==='users'"><h2>Tenant accounts</h2><article class="row" *ngFor="let u of users"><div><strong>{{u.firstName}} {{u.lastName}}</strong><small>{{u.email}} · {{u.phoneNumber}} · {{u.roles.join(', ')}}</small></div><span class="status">{{u.active?'ACTIVE':'INACTIVE'}}</span><button (click)="setStatus(u,!u.active)">{{u.active?'Deactivate':'Activate'}}</button><button (click)="setRole(u,'OWNER')">Make owner</button></article></section>
  <section class="panel" *ngIf="tab==='bookings'"><h2>All bookings</h2><article class="row" *ngFor="let b of bookings"><div><strong>{{b.propertyTitle}}</strong><small>{{b.checkIn}} to {{b.checkOut}} · {{b.location}}</small></div><span class="status">{{b.status}}</span><button *ngIf="b.status!=='CANCELLED'" class="danger" (click)="cancelBooking(b.id)">Cancel</button></article></section>
  <section class="panel" *ngIf="tab==='categories'"><h2>Categories</h2><form class="inline" (ngSubmit)="saveCategory()"><input name="categoryName" [(ngModel)]="category.name" placeholder="Name" required><input name="categoryDescription" [(ngModel)]="category.description" placeholder="Description"><button>{{category.id?'Save changes':'Add category'}}</button><button type="button" class="quiet" (click)="category={name:'',description:''}">Clear</button></form><article class="row" *ngFor="let c of categories"><div><strong>{{c.name}}</strong><small>{{c.description}}</small></div><button (click)="category=c">Edit</button><button class="danger" (click)="deleteCategory(c.id)">Delete</button></article></section>
  <section class="panel" *ngIf="tab==='complaints'"><h2>Complaints</h2><article class="row wrap" *ngFor="let c of complaints"><div><strong>{{c.subject}}</strong><small>{{c.reportedByEmail}} · {{c.description}}</small><small *ngIf="c.resolutionNote">Resolution: {{c.resolutionNote}}</small></div><span class="status">{{c.status}}</span><select #status><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option><option value="DISMISSED">Dismissed</option></select><input #note placeholder="Resolution note"><button (click)="resolve(c,status.value,note.value)">Update</button></article></section>
  <section class="panel" *ngIf="tab==='settings'"><h2>System settings</h2><form class="inline" (ngSubmit)="saveSetting()"><input name="settingKey" [(ngModel)]="setting.key" placeholder="Key" required><input name="settingValue" [(ngModel)]="setting.value" placeholder="Value" required><button>Save setting</button></form><article class="row" *ngFor="let s of settings"><div><strong>{{s.key}}</strong><small>{{s.value}}</small></div><button (click)="setting={key:s.key,value:s.value}">Edit</button></article></section></ng-container></section>`,
  styles: [`
  .page{max-width:1120px;margin:auto;padding:32px 20px;color:#172033}header{background:linear-gradient(120deg,#312e81,#6d28d9);color:#fff;border-radius:22px;padding:28px}h1{margin:6px 0;font-size:32px}header p{margin:0;opacity:.85}.eyebrow{font-size:11px;letter-spacing:.13em;font-weight:800}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:20px 0}.metrics article,.panel{background:white;border:1px solid #e2e8f0;border-radius:14px;padding:16px}.metrics small,.row small{display:block;color:#64748b}.metrics b{font-size:25px}nav{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0}button{border:0;border-radius:8px;padding:8px 11px;background:#4f46e5;color:white;font-weight:750;cursor:pointer}nav button{background:#e9e9f9;color:#3730a3}nav .selected{background:#4f46e5;color:#fff}.panel h2{margin-top:0}.row{display:flex;align-items:center;gap:8px;border-top:1px solid #edf2f7;padding:12px 0}.row>div{flex:1}.status{font-size:11px;font-weight:800;padding:5px 8px;border-radius:99px;background:#eef2ff;color:#4338ca}.danger{background:#b42318}.quiet{background:#64748b}.inline{display:flex;gap:8px;margin-bottom:14px}.inline input,.row input,.row select{padding:8px;border:1px solid #cbd5e1;border-radius:8px}.empty{color:#64748b;padding:16px;text-align:center}.error,.loading{margin:18px 0;padding:12px}.error{color:#b42318;background:#fef2f2}@media(max-width:720px){.metrics{grid-template-columns:repeat(2,1fr)}.row{align-items:flex-start;flex-wrap:wrap}.inline{flex-direction:column}}
  `]
})
export class AdminWorkspaceComponent implements OnInit {
  tabs=[{key:'properties',label:'Listings'},{key:'users',label:'Users'},{key:'bookings',label:'Bookings'},{key:'categories',label:'Categories'},{key:'complaints',label:'Complaints'},{key:'settings',label:'Settings'}]; tab='properties'; loading=true; error='';
  dashboard:AdminDashboard={totalUsers:0,activeUsers:0,totalOwners:0,totalProperties:0,pendingProperties:0,totalBookings:0,cancelledBookings:0,openComplaints:0}; users:AdminUser[]=[]; properties:Property[]=[]; bookings:Booking[]=[]; categories:Category[]=[]; complaints:Complaint[]=[]; settings:Setting[]=[]; category:Partial<Category>={name:'',description:''}; setting:Setting={key:'',value:''};
  constructor(private admin:AdminService){} ngOnInit(){this.reload();}
  reload(){this.loading=true;this.error='';this.admin.dashboard().subscribe({next:d=>{this.dashboard=d;this.admin.users().subscribe({next:u=>{this.users=u;this.admin.properties().subscribe({next:p=>{this.properties=p;this.admin.bookings().subscribe({next:b=>{this.bookings=b;this.admin.categories().subscribe({next:c=>{this.categories=c;this.admin.complaints().subscribe({next:x=>{this.complaints=x;this.admin.settings().subscribe({next:s=>{this.settings=s;this.loading=false},error:e=>this.fail(e)})},error:e=>this.fail(e)})},error:e=>this.fail(e)})},error:e=>this.fail(e)})},error:e=>this.fail(e)})},error:e=>this.fail(e)})},error:e=>this.fail(e)});}
  fail(e:any){this.error=e?.error?.message??'Unable to load administration data.';this.loading=false;} moderate(p:Property,status:'APPROVED'|'REJECTED'){this.admin.moderateProperty(p.id,status).subscribe({next:()=>this.reload(),error:e=>this.fail(e)});} deleteProperty(id:number){this.admin.deleteProperty(id).subscribe({next:()=>this.reload(),error:e=>this.fail(e)});} setStatus(u:AdminUser,active:boolean){this.admin.setUserStatus(u.id,active).subscribe({next:()=>this.reload(),error:e=>this.fail(e)});} setRole(u:AdminUser,role:'OWNER'|'TENANT'){this.admin.setUserRole(u.id,role).subscribe({next:()=>this.reload(),error:e=>this.fail(e)});} cancelBooking(id:number){this.admin.cancelBooking(id).subscribe({next:()=>this.reload(),error:e=>this.fail(e)});} saveCategory(){this.admin.saveCategory(this.category).subscribe({next:()=>{this.category={name:'',description:''};this.reload()},error:e=>this.fail(e)});} deleteCategory(id:number){this.admin.deleteCategory(id).subscribe({next:()=>this.reload(),error:e=>this.fail(e)});} resolve(c:Complaint,status:string,note:string){this.admin.resolveComplaint(c.id,status,note).subscribe({next:()=>this.reload(),error:e=>this.fail(e)});} saveSetting(){this.admin.saveSetting(this.setting).subscribe({next:()=>{this.setting={key:'',value:''};this.reload()},error:e=>this.fail(e)});}
}
